class WeaponTree:
    def __init__(self, name, element, weapons):
        self.name = name
        self.element = element
        self.weapons = weapons

class WeaponDict:
    def __init__(self):
        self.weapons = {}
    
    def add_weapon_tree(self, weapon_tree):
        self.weapons[weapon_tree.element + "_" + weapon_tree.name] = weapon_tree

mhr_weapons = WeaponDict()

mhr_weapons.add_weapon_tree(WeaponTree("Violet Mizutsune", "Fire", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Fire", "Fire", {"Greatsword", "Dual Blades", "Lance", "Hammer", "Hunting Horn"}))
mhr_weapons.add_weapon_tree(WeaponTree("Aknosom", "Fire", {"Greatsword", "Long Sword", "Dual Blades", "Lance", "Gunlance","Switch Axe", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Espinas", "Fire", {"Greatsword", "Sword & Shield", "Dual Blades", "Lance", "Hammer", "Switch Axe", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Flaming Espinas", "Fire", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Rathalos", "Fire", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Silver Rathalos", "Fire", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Anjanath", "Fire", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Gunlance", "Hammer", "Switch Axe", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Basarios", "Fire", {"Long Sword", "Hunting Horn"}))
mhr_weapons.add_weapon_tree(WeaponTree("Magma Almudron", "Fire", {"Long Sword", "Dual Blades", "Gunlance", "Hammer", "Switch Axe"}))
mhr_weapons.add_weapon_tree(WeaponTree("Hand-Me-Down", "Fire", {"Long Sword"}))
mhr_weapons.add_weapon_tree(WeaponTree("Uroktor", "Fire", {"Sword & Shield"}))
mhr_weapons.add_weapon_tree(WeaponTree("Bnahabra (Fire)", "Fire", {"Sword & Shield", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Fugen", "Fire", {"Dual Blades"}))
mhr_weapons.add_weapon_tree(WeaponTree("Rakna-Kadaki", "Fire", {"Gunlance", "Hunting Horn", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Mosgharl", "Fire", {"Hammer"}))
mhr_weapons.add_weapon_tree(WeaponTree("Rathian", "Fire", {"Hunting Horn", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Gold Rathian", "Fire", {"Hunting Horn"}))

mhr_weapons.add_weapon_tree(WeaponTree("Mizutsune", "Water", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Tetranadon", "Water", {"Greatsword", "Sword & Shield", "Lance", "Hunting Horn", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Daimyo Hermitaur", "Water", {"Greatsword", "Long Sword", "Dual Blades", "Lance", "Hunting Horn", "Switch Axe", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Shogun Ceanataur", "Water", {"Greatsword", "Long Sword", "Dual Blades", "Lance", "Hammer", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Daimyo Hermitaur & Shogun Ceanataur", "Water", {"Sword & Shield", "Gunlance"}))
mhr_weapons.add_weapon_tree(WeaponTree("Jyuratodus", "Water", {"Greatsword", "Long Sword", "Dual Blades", "Switch Axe", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Royal Ludroth", "Water", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Almudron", "Water", {"Long Sword", "Dual Blades", "Gunlance", "Hammer", "Switch Axe"}))
mhr_weapons.add_weapon_tree(WeaponTree("Azure Star", "Water", {"Long Sword"}))
mhr_weapons.add_weapon_tree(WeaponTree("Water", "Water", {"Sword & Shield"}))
mhr_weapons.add_weapon_tree(WeaponTree("Guild", "Water", {"Dual Blades"}))
mhr_weapons.add_weapon_tree(WeaponTree("Delex", "Water", {"Gunlance", "Switch Axe"}))
mhr_weapons.add_weapon_tree(WeaponTree("Vaik", "Water", {"Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Smithy", "Water", {"Insect Glaive"}))

mhr_weapons.add_weapon_tree(WeaponTree("Khezu", "Thunder", {"Greatsword", "Sword & Shield", "Dual Blades", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Astalos", "Thunder", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Zinogre", "Thunder", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Rajang", "Thunder", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Furious Rajang", "Thunder", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Narwa", "Thunder", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Thunder", "Thunder", {"Long Sword", "Dual Blades", "Lance", "Hammer", "Switch Axe", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Tobi-Kadachi", "Thunder", {"Long Sword", "Dual Blades", "Lance", "Gunlance", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Bnahabra (Thunder)", "Thunder", {"Sword & Shield"}))

mhr_weapons.add_weapon_tree(WeaponTree("Goss Harag", "Ice", {"Greatsword", "Sword & Shield", "Lance", "Hammer", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Aurora Somnacanth", "Ice", {"Greatsword", "Long Sword", "Dual Blades", "Hammer", "Hunting Horn", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Barioth", "Ice", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Lunagaron", "Ice", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Lagombi", "Ice", {"Greatsword", "Long Sword", "Dual Blades", "Gunlance", "Switch Axe", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Kushala Daora", "Ice", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Speartuna", "Ice", {"Greatsword"}))
mhr_weapons.add_weapon_tree(WeaponTree("Velkhana", "Ice", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Ice", "Ice", {"Long Sword", "Sword & Shield", "Dual Blades", "Hammer", "Hunting Horn"}))
mhr_weapons.add_weapon_tree(WeaponTree("Bnahabra (Ice)", "Ice", {"Sword & Shield", "Gunlance", "Hunting Horn", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Teostra", "Ice", {"Dual Blades"}))
mhr_weapons.add_weapon_tree(WeaponTree("Zamite", "Ice", {"Lance"}))
mhr_weapons.add_weapon_tree(WeaponTree("Magia", "Ice", {"Hunting Horn"}))

mhr_weapons.add_weapon_tree(WeaponTree("Malzeno", "Dragon", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Bone", "Dragon", {"Greatsword"}))
mhr_weapons.add_weapon_tree(WeaponTree("Gore Magala", "Dragon", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Shagaru Magala", "Dragon", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Chaotic Gore Magala", "Dragon", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Ibushi", "Dragon", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Valstrax", "Dragon", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Gaismagorm", "Dragon", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Smithy", "Dragon", {"Greatsword"}))
mhr_weapons.add_weapon_tree(WeaponTree("Death Stench", "Dragon", {"Long Sword", "Hammer", "Switch Axe", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Bnahabra (Dragon)", "Dragon", {"Sword & Shield", "Gunlance", "Hunting Horn", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Aelucanth", "Dragon", {"Dual Blades", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Guild", "Dragon", {"Dual Blades"}))
mhr_weapons.add_weapon_tree(WeaponTree("Dragon", "Dragon", {"Lance", "Switch Axe", "Charge Blade"}))

mhr_weapons.add_weapon_tree(WeaponTree("Remobra", "Poison", {"Greatsword", "Lance", "Hammer", "Switch Axe"}))
mhr_weapons.add_weapon_tree(WeaponTree("Lucent Nargacuga", "Poison", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Ore", "Poison", {"Greatsword"}))
mhr_weapons.add_weapon_tree(WeaponTree("Pukei-Pukei", "Poison", {"Greatsword", "Sword & Shield", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Rathian", "Poison", {"Greatsword", "Long Sword", "Sword & Shield", "Gunlance", "Switch Axe", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Gold Rathian", "Poison", {"Long Sword", "Sword & Shield", "Gunlance", "Switch Axe", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Chameleos", "Poison", {"Greatsword", "Dual Blades", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Chaos", "Poison", {"Greatsword", "Hunting Horn"}))
mhr_weapons.add_weapon_tree(WeaponTree("Espinas", "Poison", {"Long Sword", "Dual Blades", "Gunlance", "Hunting Horn", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Flaming Espinas", "Poison", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Great Wroggi", "Poison", {"Long Sword", "Sword & Shield", "Dual Blades", "Hammer"}))
mhr_weapons.add_weapon_tree(WeaponTree("Poison", "Poison", {"Long Sword", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Antique Machina", "Poison", {"Dual Blades", "Hammer"}))
mhr_weapons.add_weapon_tree(WeaponTree("Basarios", "Poison", {"Lance", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Spio", "Poison", {"Lance"}))

mhr_weapons.add_weapon_tree(WeaponTree("Felyne", "Paralysis", {"Greatsword", "Sword & Shield", "Dual Blades", "Switch Axe", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Great Baggi", "Paralysis", {"Long Sword"}))
mhr_weapons.add_weapon_tree(WeaponTree("Bnahabra (Paralysis)", "Paralysis", {"Sword & Shield", "Gunlance", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Khezu", "Paralysis", {"Dual Blades"}))
mhr_weapons.add_weapon_tree(WeaponTree("Jelly", "Paralysis", {"Dual Blades"}))
mhr_weapons.add_weapon_tree(WeaponTree("Volvidon", "Paralysis", {"Lance", "Gunlance", "Hammer", "Switch Axe", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Hornetaur", "Paralysis", {"Lance"}))
mhr_weapons.add_weapon_tree(WeaponTree("Chaos", "Paralysis", {"Lance"}))
mhr_weapons.add_weapon_tree(WeaponTree("Paralysis", "Paralysis", {"Hammer", "Hunting Horn", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Vespoid", "Paralysis", {"Hunting Horn"}))
mhr_weapons.add_weapon_tree(WeaponTree("Spio", "Paralysis", {"Hunting Horn"}))

mhr_weapons.add_weapon_tree(WeaponTree("Somnacanth", "Sleep", {"Greatsword", "Long Sword", "Dual Blades", "Hammer", "Hunting Horn", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Shell-Studded", "Sleep", {"Greatsword", "Sword & Shield", "Gunlance", "Switch Axe"}))
mhr_weapons.add_weapon_tree(WeaponTree("Antique Machina", "Sleep", {"Long Sword", "Sword & Shield", "Lance", "Gunlance", "Hunting Horn", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Great Baggi", "Sleep", {"Sword & Shield", "Lance", "Gunlance", "Switch Axe"}))
mhr_weapons.add_weapon_tree(WeaponTree("Smithy", "Sleep", {"Dual Blades"}))
mhr_weapons.add_weapon_tree(WeaponTree("Melahoa", "Sleep", {"Lance"}))
mhr_weapons.add_weapon_tree(WeaponTree("Guild", "Sleep", {"Hammer"}))

mhr_weapons.add_weapon_tree(WeaponTree("Magnamalo", "Blast", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Scorned Magnamalo", "Blast", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Gunlance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade", "Insect Glaive"}))
mhr_weapons.add_weapon_tree(WeaponTree("Teostra", "Blast", {"Greatsword", "Long Sword", "Sword & Shield", "Dual Blades", "Lance", "Hammer", "Hunting Horn", "Switch Axe", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Antique Machina", "Blast", {"Greatsword", "Dual Blades"}))
mhr_weapons.add_weapon_tree(WeaponTree("Bazelgeuse", "Blast", {"Long Sword", "Dual Blades", "Lance", "Gunlance", "Hunting Horn", "Switch Axe"}))
mhr_weapons.add_weapon_tree(WeaponTree("Seething Bazelgeuse", "Blast", {"Long Sword", "Dual Blades", "Lance", "Gunlance", "Hunting Horn", "Switch Axe"}))
mhr_weapons.add_weapon_tree(WeaponTree("Blood Orange Bishaten", "Blast", {"Sword & Shield", "Hammer", "Switch Axe"}))
mhr_weapons.add_weapon_tree(WeaponTree("Pyre Rakna-Kadaki", "Blast", {"Gunlance", "Hunting Horn", "Charge Blade"}))
mhr_weapons.add_weapon_tree(WeaponTree("Bombadgy", "Blast", {"Hunting Horn"}))
mhr_weapons.add_weapon_tree(WeaponTree("Magia", "Blast", {"Insect Glaive"}))

# for weapon in mhr_weapons.weapons:
#     # print(mhr_weapons.weapons[weapon], "\n")
#     if mhr_weapons.weapons[weapon].element == "Fire":
#         if "Greatsword" in mhr_weapons.weapons[weapon].weapons:
#             print(mhr_weapons.weapons[weapon].name, "\n")